create database ecommerce;

use ecommerce;

-- create category table query
CREATE TABLE Category (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- create product table query
CREATE TABLE Product (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    long_description TEXT,
    price DECIMAL(10, 2) NOT NULL,
    discounted_price DECIMAL(10, 2) DEFAULT NULL,
    image_url VARCHAR(500),
    stock INT DEFAULT 0,
    category_id INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES Category(id) ON DELETE SET NULL
);

-- insert categories into category table
INSERT INTO Category (name, description) VALUES
('Electronics', 'Devices, gadgets, and accessories'),
('Fashion', 'Clothing, shoes, and accessories for men, women, and children'),
('Home & Kitchen', 'Furniture, decor, and kitchen appliances'),
('Books', 'Books across different genres and categories'),
('Toys & Games', 'Toys, puzzles, and games for children and adults'),
('Health & Beauty', 'Health care products, cosmetics, and personal care items'),
('Sports & Outdoors', 'Sporting goods, outdoor gear, and fitness equipment'),
('Automotive', 'Car accessories, tools, and spare parts'),
('Groceries', 'Daily essentials, food, and beverages'),
('Jewelry', 'Rings, necklaces, bracelets, and other jewelry items');

-- insert products data into product table(100 rows)
INSERT INTO Product 
    (name, description, long_description, price, discounted_price, image_url, stock, category_id) 
VALUES 
    ('IKEA KALLAX Shelf Unit', 
     'Versatile shelf unit with multiple compartments.', 
     'The IKEA KALLAX Shelf Unit is a versatile storage solution that fits in any room. Featuring a modern design with multiple compartments, it can be used to store books, decor items, and more. Made from durable materials, it can be customized with boxes and inserts to suit your needs.', 
     129.00, 
     99.00, 
     'https://live.staticflickr.com/5648/22098635473_09e5edca16_b.jpg', 
     200, 
     3),
     
    ('Nespresso Vertuo Plus Coffee Maker', 
     'Single-serve coffee maker for rich coffee and espresso.', 
     'The Nespresso Vertuo Plus Coffee Maker brews both coffee and espresso with rich crema at the touch of a button. Its innovative brewing technology uses barcodes on the coffee pods to optimize brewing parameters for each blend. A perfect addition for coffee lovers who enjoy variety.', 
     199.99, 
     179.99, 
     'https://live.staticflickr.com/7616/16769462027_d7758545e8_b.jpg', 
     150, 
     3),
     
    ('Instant Pot Duo 7-in-1 Electric Pressure Cooker', 
     'Multi-functional cooker with pressure cooking, slow cooking, and more.', 
     'The Instant Pot Duo is a 7-in-1 multi-functional electric pressure cooker that replaces several kitchen appliances. It features pressure cooking, slow cooking, sautéing, steaming, and more, all in one device. Perfect for busy families looking to prepare meals quickly and easily.', 
     89.95, 
     79.95, 
     'https://live.staticflickr.com/65535/49907000991_25d076b08d_b.jpg', 
     300, 
     3),
     
    ('Cuisinart 14-Cup Food Processor', 
     'High-capacity food processor with stainless steel blades.', 
     'The Cuisinart 14-Cup Food Processor is designed to handle all your food prep tasks, from chopping to slicing. With a powerful motor and stainless steel blades, it offers exceptional performance. The large capacity bowl is perfect for family-sized meals or meal prep.', 
     199.00, 
     169.00, 
     'https://live.staticflickr.com/4543/24462629568_ab92ea63d4_b.jpg', 
     180, 
     3),
     
    ('Dyson V11 Torque Drive Cordless Vacuum', 
     'High-performance cordless vacuum with intelligent cleaning.', 
     'The Dyson V11 Torque Drive Cordless Vacuum is engineered for deep cleaning. It automatically adapts to different floor types, providing powerful suction on carpets and hard floors. With up to 60 minutes of run time, it is perfect for whole-house cleaning.', 
     599.99, 
     499.99, 
     'https://www.trustedreviews.com/wp-content/uploads/sites/54/2024/03/Dyson-V15s-Detect-Submarine-carpet-floor-head.jpg', 
     120, 
     3),
     
    ('Lodge Cast Iron Skillet', 
     'Durable cast iron skillet for cooking and baking.', 
     'The Lodge Cast Iron Skillet is pre-seasoned and ready to use right out of the box. Ideal for searing, sautéing, baking, and frying, it offers unparalleled heat retention and even cooking. This versatile skillet is perfect for stovetop or oven use.', 
     29.90, 
     24.90, 
     'https://live.staticflickr.com/2559/3799011105_a2ff30b567_b.jpg', 
     500, 
     3),
     
    ('Hamilton Beach Slow Cooker', 
     'Programmable slow cooker with temperature probe.', 
     'The Hamilton Beach Slow Cooker features a programmable timer and temperature probe for precise cooking. It’s perfect for stews, soups, and tenderizing meats. The removable stoneware pot makes serving and cleaning easy.', 
     49.99, 
     39.99, 
     'https://upload.wikimedia.org/wikipedia/commons/4/42/Hamilton_Beach_slow_cooker_with_thermometer.jpg', 
     250, 
     3),
     
    ('Ninja Professional Blender', 
     'High-power blender for smoothies and more.', 
     'The Ninja Professional Blender is designed for professional-grade performance. With a powerful 1,000-watt motor and a total crushing pitcher, it easily blends ice and frozen fruits for smoothies, soups, and more. Ideal for healthy living.', 
     89.99, 
     79.99, 
     'https://live.staticflickr.com/65535/49907001146_d8bc5271fc_b.jpg', 
     300, 
     3),
     
    ('Breville Smart Oven Air Fryer', 
     'Countertop oven with air frying capability.', 
     'The Breville Smart Oven Air Fryer combines the functions of an air fryer and a convection oven, allowing you to cook a variety of meals quickly and healthily. It features smart technology to ensure even cooking and perfect results every time.', 
     299.99, 
     249.99, 
     'https://live.staticflickr.com/666/23752613235_591ae15fb5_b.jpg', 
     80, 
     3),
     
    ('KitchenAid Artisan Stand Mixer', 
     'Iconic stand mixer with powerful motor and multiple attachments.', 
     'The KitchenAid Artisan Stand Mixer features a 5-quart stainless steel bowl and a powerful 325-watt motor. It comes with multiple attachments for various cooking tasks, including kneading dough, mixing batter, and whipping cream. A must-have for any serious home baker.', 
     429.99, 
     399.99, 
     'https://live.staticflickr.com/7059/6799745062_db78c179b6_b.jpg', 
     90, 
     3);
     
       INSERT INTO Product 
    (name, description, long_description, price, discounted_price, image_url, stock, category_id) 
VALUES 
    ('LEGO Classic Bricks and Animals', 
     'Versatile LEGO set with colorful bricks and animal figures.', 
     'The LEGO Classic Bricks and Animals set includes a variety of colorful LEGO bricks and animal figures, allowing kids to unleash their creativity. With endless building possibilities, this set encourages imaginative play and fine motor skills development.', 
     29.99, 
     24.99, 
     'https://myplay.ua/tmp/cache/images/a9/364/1-360416-360-2000x2000-r.webp', 
     300, 
     5),
     
    ('Hasbro Monopoly Board Game', 
     'Classic board game of property trading and strategy.', 
     'The Hasbro Monopoly Board Game is a timeless family favorite that involves buying, selling, and trading properties to bankrupt opponents. With its iconic gameplay and colorful game pieces, it provides hours of fun for players of all ages.', 
     19.99, 
     16.99, 
     'https://myplay.ua/tmp/cache/images/9f/6a5/1-374409-360-2000x2000-r.webp', 
     200, 
     5),
     
    ('Mattel Uno Card Game', 
     'Fast-paced card game for family and friends.', 
     'The Mattel Uno Card Game is a fast-paced game where players aim to match colors and numbers to be the first to get rid of all their cards. With its simple rules and exciting gameplay, it’s perfect for family gatherings and game nights.', 
     12.99, 
     10.99, 
     'https://myplay.ua/tmp/cache/images/fa/00e/1-330810-360-2000x2000-r.webp', 
     500, 
     5),
     
    ('Ravensburger 1000 Piece Puzzle', 
     'Challenging and colorful jigsaw puzzle.', 
     'The Ravensburger 1000 Piece Puzzle features a beautiful and colorful design that provides hours of challenging fun. Made with high-quality materials, the pieces fit perfectly and create a stunning image upon completion, making it ideal for puzzle enthusiasts.', 
     24.99, 
     22.00, 
     'https://www.funskoolindia.com/storage/product/709/HL1LGSSI5UeRbR3WmryS1wrTKYktUhgJl8N2fEiM.jpg', 
     150, 
     5),
     
    ('Barbie Dreamhouse Dollhouse', 
     'Spacious and stylish dollhouse for Barbie and friends.', 
     'The Barbie Dreamhouse Dollhouse is a multi-story home featuring rooms for cooking, sleeping, and entertaining. With interactive features and stylish decor, it encourages imaginative play as kids create stories and adventures for their Barbie dolls.', 
     199.99, 
     179.99, 
     'https://live.staticflickr.com/5691/31237236092_69fc2d646f_b.jpg', 
     80, 
     5),
     
    ('Nerf N-Strike Elite Disruptor Blaster', 
     'Pump-action blaster for outdoor fun.', 
     'The Nerf N-Strike Elite Disruptor Blaster offers exciting outdoor play with its pump-action mechanism. It features a rotating drum that holds six darts and can shoot them up to 90 feet. Perfect for friendly battles and active playtime!', 
     24.99, 
     19.99, 
     'https://live.staticflickr.com/7476/26840542216_3effe5515c_b.jpg', 
     200, 
     5),
     
    ('Play-Doh Modeling Compound 10-Pack', 
     'Colorful modeling compound for creative play.', 
     'The Play-Doh Modeling Compound 10-Pack includes a variety of vibrant colors for endless creativity. Kids can mold and shape their creations, enhancing their artistic skills and sparking their imagination. Perfect for crafting and sensory play!', 
     19.99, 
     15.99, 
     'https://myplay.ua/tmp/cache/images/db/af5/1-362233-360-2000x2000-r.webp', 
     400, 
     5),
     
    ('VTech Sit-to-Stand Learning Walker', 
     'Interactive walker for infants and toddlers.', 
     'The VTech Sit-to-Stand Learning Walker grows with your child, offering both a seated play mode and a standing walker mode. It features interactive buttons, music, and lights, helping develop motor skills and encouraging exploration.', 
     49.99, 
     44.99, 
     'https://live.staticflickr.com/65535/50842018142_1e8db72b27_b.jpg', 
     300, 
     5),
     
    ('Hot Wheels 50-Car Pack', 
     'Collection of 50 Hot Wheels cars for collectors and kids.', 
     'The Hot Wheels 50-Car Pack includes a variety of die-cast cars, perfect for collectors and kids alike. Each car features unique designs and styles, encouraging imaginative play and racing adventures.', 
     59.99, 
     54.99, 
     'https://myplay.ua/tmp/cache/images/6f/2b0/1-004996-360-2000x2000-r.webp', 
     250, 
     5),
     
    ('Giant Jenga Game', 
     'Outdoor stacking game for all ages.', 
     'The Giant Jenga Game brings classic fun to your backyard or game night. Players take turns removing blocks from the stack without toppling it. The suspense builds as the tower grows taller, making it an exciting game for everyone!', 
     39.99, 
     34.99, 
     'https://upload.wikimedia.org/wikipedia/commons/8/8f/Tetris_Jenga.jpg', 
     180, 
     5);
     
     
     INSERT INTO Product 
    (name, description, long_description, price, discounted_price, image_url, stock, category_id) 
VALUES 
    ('The Midnight Library by Matt Haig', 
     'A novel about a library between life and death.', 
     'In "The Midnight Library," Nora Seed finds herself in a library that allows her to explore the various paths her life could have taken. Each book in the library represents a different life she could have lived, challenging her views on regret and fulfillment.', 
     16.99, 
     14.99, 
     'https://upload.wikimedia.org/wikipedia/commons/6/60/The_midnight_library_travels_england_2021.jpg', 
     250, 
     4),
     
    ('Where the Crawdads Sing by Delia Owens', 
     'A coming-of-age story intertwined with a murder mystery.', 
     'Set in the marshes of North Carolina, "Where the Crawdads Sing" tells the story of Kya, an isolated girl who grows up alone. When a murder occurs, she becomes a prime suspect, exploring themes of loneliness and resilience in the natural world.', 
     24.99, 
     19.99, 
     'https://i0.pickpik.com/photos/500/775/581/book-pitched-book-pages-paper-preview.jpg', 
     300, 
     4),
     
    ('Educated by Tara Westover', 
     'A memoir about a woman who grows up in a strict and abusive household.', 
     'In "Educated," Tara Westover recounts her quest for knowledge and self-discovery despite her upbringing in a strict survivalist family in rural Idaho. This powerful memoir explores themes of education, resilience, and the pursuit of understanding.', 
     27.00, 
     22.00, 
     'https://miro.medium.com/v2/resize:fit:1358/1*NcOp6P4VIaaVs7aFCfm2tQ.jpeg', 
     150, 
     4),
     
    ('The Vanishing Half by Brit Bennett', 
     'A multi-generational tale about twin sisters and their diverging paths.', 
     'In "The Vanishing Half," twin sisters Stella and Desiree grow up in a small Southern Black community. When Stella passes as white, their lives diverge dramatically, exploring themes of identity, race, and family over several decades.', 
     18.99, 
     16.99, 
     'https://api.ndla.no/image-api/raw/bok.jpg', 
     200, 
     4),
     
    ('Becoming by Michelle Obama', 
     'The former First Lady’s memoir about her life and experiences.', 
     'In "Becoming," Michelle Obama shares her journey from the South Side of Chicago to the White House. She reflects on her roots, her role as a mother, and her time as the First Lady, inspiring readers to embrace their own stories.', 
     32.00, 
     28.00, 
     'https://live.staticflickr.com/65535/49057435748_86fec79d70_c.jpg', 
     100, 
     4),
     
    ('The Silent Patient by Alex Michaelides', 
     'A psychological thriller about a woman who stops speaking after a crime.', 
     'In "The Silent Patient," Alicia Berenson, a famous painter, is found guilty of murdering her husband and stops speaking. Her therapist, determined to uncover the truth, delves into her past, revealing dark secrets and twists.', 
     26.00, 
     22.00, 
     'https://images.pexels.com/photos/69004/pexels-photo-69004.jpeg', 
     200, 
     4),
     
    ('The Great Gatsby by F. Scott Fitzgerald', 
     'A classic novel about the American Dream and the Jazz Age.', 
     'Set in the 1920s, "The Great Gatsby" follows the mysterious Jay Gatsby and his obsession with Daisy Buchanan. Through the eyes of narrator Nick Carraway, Fitzgerald explores themes of wealth, love, and the American Dream.', 
     15.99, 
     12.99, 
     'https://live.staticflickr.com/3206/3041823040_274450acb7_b.jpg', 
     350, 
     4),
     
    ('1984 by George Orwell', 
     'A dystopian novel about totalitarianism and surveillance.', 
     'George Orwell’s "1984" depicts a chilling future under an oppressive regime where individuality and freedom are crushed. Through the story of Winston Smith, Orwell explores themes of surveillance, propaganda, and the manipulation of truth.', 
     14.99, 
     11.99, 
     'https://mir-s3-cdn-cf.behance.net/project_modules/disp/78ece225035097.56356706ba190.jpg', 
     400, 
     4),
     
    ('The Alchemist by Paulo Coelho', 
     'A philosophical novel about pursuing one’s dreams.', 
     'In "The Alchemist," Santiago, a young shepherd, embarks on a journey to discover his personal legend and fulfill his dreams. Coelho’s timeless tale explores the importance of listening to one’s heart and following one’s path.', 
     18.00, 
     15.00, 
     'https://live.staticflickr.com/2637/4114624736_325755ffc5_c.jpg', 
     250, 
     4),
     
    ('The Subtle Art of Not Giving a F*ck by Mark Manson', 
     'A counterintuitive approach to living a good life.', 
     'In "The Subtle Art of Not Giving a F*ck," Mark Manson challenges conventional self-help advice and offers a refreshing perspective on living a meaningful life. He emphasizes the importance of embracing struggles and limitations to find true happiness.', 
     24.99, 
     21.99, 
     'https://live.staticflickr.com/4356/36528427295_423e820a8d_b.jpg', 
     300, 
     4);
     
     INSERT INTO Product 
    (name, description, long_description, price, discounted_price, image_url, stock, category_id) 
VALUES 
    ('Apple iPhone 14 Pro Max', 
     'Latest Apple iPhone with advanced camera and performance.', 
     'The Apple iPhone 14 Pro Max features a 6.7-inch Super Retina XDR display, a powerful A16 Bionic chip, and a Pro camera system with 48MP main sensor. The device also includes Face ID, 5G connectivity, and iOS 16, offering top-notch performance and security.', 
     1099.00, 
     999.00, 
     'https://www.trustedreviews.com/wp-content/uploads/sites/54/2022/10/iphone14proproductshots-1-4.jpeg', 
     150, 
     1),
     
    ('Samsung Galaxy S23 Ultra', 
     'Flagship Android smartphone with cutting-edge features.', 
     'The Samsung Galaxy S23 Ultra boasts a 6.8-inch Dynamic AMOLED display, Snapdragon 8 Gen 2 processor, and a 200MP quad-camera system. With S-Pen support and a 5000mAh battery, it is perfect for power users who demand the best in performance and productivity.', 
     1199.00, 
     1099.00, 
     'https://www.trustedreviews.com/wp-content/uploads/sites/54/2023/02/Samsung-Galaxy-S23-Ultra-review-5.jpg', 
     200, 
     1),
     
    ('Sony WH-1000XM5 Headphones', 
     'Noise-canceling wireless headphones with premium sound.', 
     'Sony WH-1000XM5 offers industry-leading noise cancellation and high-resolution audio with LDAC support. The over-ear headphones provide 30 hours of battery life, voice assistant integration, and touch controls for a seamless, immersive listening experience.', 
     399.99, 
     349.99, 
     'https://www.trustedreviews.com/wp-content/uploads/sites/54/2018/09/RXV06632.jpg', 
     500, 
     1),
     
    ('Apple MacBook Pro 14-inch', 
     'High-performance laptop with M2 Pro chip.', 
     'The Apple MacBook Pro 14-inch is powered by the M2 Pro chip, providing superior performance for professional tasks. It features a Liquid Retina XDR display, a 1080p FaceTime camera, and up to 17 hours of battery life, making it perfect for creative professionals and developers.', 
     1999.00, 
     1799.00, 
     'https://www.trustedreviews.com/wp-content/uploads/sites/54/2023/10/Screenshot-2023-10-31-001403.png', 
     120, 
     1),
     
    ('LG C2 OLED 65-inch TV', 
     'OLED TV with 4K HDR and Dolby Vision support.', 
     'The LG C2 OLED 65-inch TV offers stunning picture quality with perfect black levels, vibrant colors, and infinite contrast. Powered by the α9 Gen 5 AI Processor 4K, this TV supports Dolby Vision, HDR10, and gaming features like VRR and ALLM for the ultimate entertainment experience.', 
     1899.00, 
     1699.00, 
     'https://www.trustedreviews.com/wp-content/uploads/sites/54/2024/06/Samsung55Q80DAngleLeft.jpg', 
     80, 
     1),
     
    ('Bose SoundLink Revolve+ II', 
     'Portable Bluetooth speaker with 360-degree sound.', 
     'Bose SoundLink Revolve+ II delivers true 360-degree sound for consistent, uniform coverage. With up to 17 hours of battery life, water-resistant design, and seamless Bluetooth pairing, it’s perfect for both indoor and outdoor use.', 
     329.99, 
     299.99, 
     'https://www.trustedreviews.com/wp-content/uploads/sites/54/2024/02/Kitsound-Boombar-30-3-scaled.jpg', 
     400, 
     1),
     
    ('Dyson V15 Detect Cordless Vacuum', 
     'Cordless vacuum with laser dust detection.', 
     'The Dyson V15 Detect is the most powerful, intelligent cordless vacuum, featuring laser dust detection and a high-torque cleaner head. It automatically adjusts suction power based on the amount of dust, ensuring deep cleaning for all surfaces.', 
     749.99, 
     699.99, 
     'https://www.trustedreviews.com/wp-content/uploads/sites/54/2021/11/Best-cordless-vacuum-cleaner-2022.jpg', 
     300, 
     1),
     
    ('GoPro HERO11 Black', 
     'Action camera with 5.3K video and HyperSmooth stabilization.', 
     'The GoPro HERO11 Black offers stunning 5.3K video recording at 60fps and 27MP photos. It includes HyperSmooth 5.0 video stabilization, waterproofing up to 33 feet, and advanced features like Horizon Lock and voice control, making it perfect for adventure filming.', 
     499.99, 
     449.99, 
     'https://www.trustedreviews.com/wp-content/uploads/sites/54/2022/09/GoPro-Hero11-Black-15-scaled.jpg', 
     600, 
     1),
     
    ('Amazon Echo Dot (5th Gen)', 
     'Smart speaker with Alexa voice assistant and improved sound.', 
     'Amazon Echo Dot (5th Gen) is a compact smart speaker with improved sound quality and Alexa integration. It allows you to control smart home devices, play music, set reminders, and much more using just your voice. Perfect for any room in the house.', 
     49.99, 
     39.99, 
     'https://www.trustedreviews.com/wp-content/uploads/sites/54/2022/03/Trouble-understanding-orange-scaled.jpg', 
     1000, 
     1),
     
    ('Canon EOS R6 Mirrorless Camera', 
     'Full-frame mirrorless camera with 4K video and fast autofocus.', 
     'The Canon EOS R6 is a powerful full-frame mirrorless camera designed for both photography and videography. It features a 20.1MP CMOS sensor, 4K 60fps video recording, and Dual Pixel autofocus for sharp, detailed images. Perfect for enthusiasts and professionals alike.', 
     2499.00, 
     2299.00, 
     'https://www.gigaparts.com/media/catalog/product/cache/002dc70ccef261c78c46589b619436fc/h/r/hr_6d_markii_ef24-105_is_ii_usm_frontopen_cl_1.jpg', 
     150, 
     1);


INSERT INTO Product 
    (name, description, long_description, price, discounted_price, image_url, stock, category_id) 
VALUES 
    ('Nike Air Max 270 Sneakers', 
     'Lightweight, stylish sneakers with Air cushioning for comfort.', 
     'Nike Air Max 270 sneakers combine style and comfort with their large Air Max unit in the heel for cushioned support. The breathable mesh upper provides ventilation for long-lasting comfort, while the sleek design makes them suitable for both casual wear and athletic activities.', 
     160.00, 
     140.00, 
     'https://cdn12.picryl.com/photo/2016/12/31/shoes-sports-shoes-sneakers-sports-267724-1024.jpg', 
     200, 
     2),
     
    ('Zara Faux Leather Biker Jacket', 
     'Trendy faux leather jacket with a classic biker design.', 
     'This Zara Faux Leather Biker Jacket offers a modern take on a classic style. Made from high-quality synthetic materials, it features an asymmetric front zip, notched lapels, and zippered pockets for a chic and edgy look. Perfect for layering over casual outfits or dressing up for a night out.', 
     79.90, 
     65.00, 
     'https://i2.pickpik.com/photos/224/780/957/girl-motorcycle-leather-jacket-ride-preview.jpg', 
     150, 
     2),
     
    ('Gucci GG Marmont Leather Bag', 
     'Iconic luxury leather bag with a quilted chevron design and GG logo.', 
     'The Gucci GG Marmont is a luxurious shoulder bag crafted from soft matelassé chevron leather with an antique gold-tone GG logo. With its adjustable chain strap and spacious interior, it combines elegance with practicality, making it a versatile accessory for both day and evening use.', 
     2350.00, 
     2200.00, 
     'https://cdn1.jolicloset.com/img4/detail4b/2024/08/1455204-1/handbags-gucci.jpg', 
     50, 
     2),
     
    ('Levi\'s 501 Original Fit Jeans', 
     'Timeless straight-leg jeans with a classic button fly.', 
     'The Levi\'s 501 jeans are a wardrobe staple, offering a timeless straight-leg silhouette and durable construction. Made from 100% cotton, they feature a button fly and signature five-pocket styling. These jeans provide a classic fit that never goes out of style, making them a reliable choice for any casual occasion.', 
     89.50, 
     75.00, 
     'https://upload.wikimedia.org/wikipedia/commons/b/b2/Jeans_MET_1978.175.2_B.jpg', 
     300, 
     2),
     
    ('Adidas Ultraboost 22 Running Shoes', 
     'High-performance running shoes with responsive Boost cushioning.', 
     'Designed for long-distance runners, the Adidas Ultraboost 22 features Boost midsole technology for energy return and responsive cushioning. The Primeknit upper adapts to your foot, providing a snug, supportive fit. These shoes are ideal for running on various terrains while ensuring comfort and performance.', 
     190.00, 
     170.00, 
     'https://pixahive.com/wp-content/uploads/2020/10/Gym-shoes-153180-pixahive.jpg', 
     250, 
     2),
     
    ('Burberry Classic Trench Coat', 
     'Luxurious double-breasted trench coat made from cotton gabardine.', 
     'A timeless investment, the Burberry Classic Trench Coat is made from cotton gabardine, a fabric invented by Burberry’s founder. It features a double-breasted front, a belt to cinch the waist, and a signature check lining. This iconic outerwear piece offers both elegance and functionality for any wardrobe.', 
     2250.00, 
     2100.00, 
     'https://live.staticflickr.com/8034/7953705824_d8f4c027d2.jpg', 
     100, 
     2),
     
    ('Ray-Ban Aviator Sunglasses', 
     'Classic aviator sunglasses with polarized lenses and metal frames.', 
     'Originally designed for U.S. aviators, the Ray-Ban Aviator sunglasses are a timeless style icon. Featuring a thin metal frame and polarized lenses, they provide excellent UV protection and a sleek, minimalist aesthetic. Suitable for all face shapes, they remain a popular choice for outdoor wear.', 
     178.00, 
     150.00, 
     'https://upload.wikimedia.org/wikipedia/commons/8/82/Ray-Ban_Aviator_Shooter_RB3139-001_3N_%28G-15_lenses%29_Size_62_09_160_Lens_base_6.jpg', 
     500, 
     2),
     
    ('Chanel No. 5 Eau de Parfum', 
     'Timeless floral fragrance with notes of jasmine and rose.', 
     'Chanel No. 5 is an iconic fragrance that has stood the test of time since its launch in 1921. It is a sophisticated blend of floral and aldehyde notes, including jasmine, rose, and sandalwood. This classic scent embodies elegance and femininity, making it a staple in luxury perfumery.', 
     146.00, 
     130.00, 
     'https://upload.wikimedia.org/wikipedia/commons/4/4e/Chanel_N%C2%B05_-_2.jpg', 
     400, 
     2),
     
    ('H&M Cotton T-Shirt', 
     'Basic soft cotton t-shirt, perfect for everyday wear.', 
     'A basic wardrobe essential, the H&M Cotton T-Shirt is made from soft, breathable cotton and designed for a comfortable fit. It features a crew neckline and short sleeves, making it versatile for layering or wearing on its own for a casual, laid-back look.', 
     12.99, 
     10.99, 
     'https://cdn.printerval.com/unsafe/960x960/asset.prtvstatic.com/2023/08/03/64cb524e100195.09473818.jpg', 
     1000, 
     2),
     
    ('Uniqlo HeatTech Thermal Leggings', 
     'Warm, moisture-wicking leggings for cold weather comfort.', 
     'Uniqlo\'s HeatTech leggings are crafted with innovative fabric that retains body heat, providing warmth in cold weather without being bulky. They are moisture-wicking and stretchable, making them perfect for layering under winter clothes or wearing as activewear in chilly conditions.', 
     24.90, 
     20.00, 
     'https://images.pexels.com/photos/6957883/pexels-photo-6957883.jpeg', 
     600, 
     2);


INSERT INTO Product 
    (name, description, long_description, price, discounted_price, image_url, stock, category_id) 
VALUES 
    ('Meguiar\'s Ultimate Liquid Wax', 
     'Premium synthetic wax for a long-lasting shine.', 
     'Meguiar\'s Ultimate Liquid Wax is a premium synthetic wax that provides a long-lasting, high-gloss finish to your vehicle. Its hydrophobic polymer technology repels water, ensuring that your car stays cleaner for longer while providing UV protection to prevent paint damage.', 
     24.99, 
     19.99, 
     'https://upload.wikimedia.org/wikipedia/commons/f/fd/Valvoline_Max_Life_Multi-Vehicle_ATF_Rear.jpg', 
     150, 
     8),
     
    ('Bosch Icon Wiper Blades', 
     'Durable and efficient wiper blades for clear visibility.', 
     'Bosch Icon Wiper Blades are designed to provide superior visibility and durability. With a patented beam design, these wipers flex to the curvature of your windshield, ensuring even pressure distribution for a streak-free wipe in all weather conditions.', 
     29.99, 
     24.99, 
     'https://catalog.polo.blue/_spoko/5K6955427A-5K6955427D-aero-wiper-blade-6_Zwkj0m.webp', 
     100, 
     8),
     
    ('Goodyear Assurance WeatherReady All-Season Tires', 
     'All-season tires for reliable performance in any weather.', 
     'The Goodyear Assurance WeatherReady All-Season Tires are designed for confident traction and handling in both wet and dry conditions. With a unique tread design, these tires provide excellent grip, making them suitable for all-year-round use.', 
     120.00, 
     110.00, 
     'https://live.staticflickr.com/3020/3028063648_96a04c443e_b.jpg', 
     80, 
     8),
     
    ('ACDelco Professional Battery', 
     'Reliable automotive battery for dependable performance.', 
     'The ACDelco Professional Battery is engineered for durability and reliable performance. This maintenance-free battery is designed to withstand harsh conditions, ensuring your vehicle starts every time. Perfect for a variety of vehicle makes and models.', 
     129.99, 
     109.99, 
     'https://live.staticflickr.com/8232/8544025466_949221402b_b.jpg', 
     60, 
     8),
     
    ('Husky 5-Piece Tool Set', 
     'Essential hand tools for automotive repairs and maintenance.', 
     'The Husky 5-Piece Tool Set includes essential hand tools for all your automotive repair and maintenance needs. Each tool is made from durable materials and designed for comfort, making it easy to tackle any job, big or small.', 
     49.99, 
     39.99, 
     'https://upload.wikimedia.org/wikipedia/commons/5/50/Husky_tool_set.jpg', 
     200, 
     8),
     
    ('Rugged Ridge Floor Liners', 
     'Heavy-duty floor liners for ultimate protection.', 
     'Rugged Ridge Floor Liners are designed to provide maximum protection for your vehicle’s interior. Made from durable, weather-resistant materials, these liners trap dirt and moisture, making them easy to clean and maintain.', 
     99.99, 
     89.99, 
     'https://catalog.polo.blue/_spoko/6R106150282V-rubber-floor-mats-lhd-front-2_2tslmU.webp', 
     120, 
     8),
     
    ('Valvoline Advanced Full Synthetic Motor Oil', 
     'High-performance motor oil for engine protection.', 
     'Valvoline Advanced Full Synthetic Motor Oil offers superior protection against engine wear and deposits. Formulated with advanced additives, it helps maintain optimal engine performance and efficiency in extreme temperatures.', 
     29.99, 
     24.99, 
     'https://live.staticflickr.com/2909/14061604449_a5ab3b5f8c_b.jpg', 
     150, 
     8),
     
    ('Cobra RAD 480i Radar Detector', 
     'Advanced radar detector with GPS capabilities.', 
     'The Cobra RAD 480i Radar Detector features advanced radar detection technology with GPS capabilities. It provides alerts for speed traps, red light cameras, and other hazards, helping you stay safe and informed on the road.', 
     199.99, 
     179.99, 
     'https://live.staticflickr.com/919/29403809508_f68cb679fc_b.jpg', 
     80, 
     8),
     
    ('Thule Motion XT Rooftop Cargo Carrier', 
     'Spacious cargo carrier for additional storage.', 
     'The Thule Motion XT Rooftop Cargo Carrier is designed for extra storage on road trips. With a sleek aerodynamic design and easy-to-use features, it provides ample space for luggage, camping gear, and more, keeping your vehicle organized.', 
     649.99, 
     599.99, 
     'https://live.staticflickr.com/4702/38693238415_b03860ae7e_b.jpg', 
     40, 
     8),
     
    ('WeatherTech Stone & Bug Deflector', 
     'Durable deflector for protecting your vehicle from debris.', 
     'The WeatherTech Stone & Bug Deflector is designed to protect your vehicle’s hood and windshield from stones, bugs, and other debris. Made from durable acrylic material, it enhances the look of your vehicle while providing superior protection.', 
     79.99, 
     69.99, 
     'https://m.media-amazon.com/images/I/51DecnE+hML.jpg', 
     100, 
     8);


INSERT INTO Product 
    (name, description, long_description, price, discounted_price, image_url, stock, category_id) 
VALUES 
    ('Organic Bananas', 
     'Fresh and sweet organic bananas.', 
     'These organic bananas are perfect for snacking or adding to smoothies. They are grown without synthetic pesticides and fertilizers, ensuring a healthy choice for you and your family.', 
     1.29, 
     1.00, 
     'https://www.stockvault.net/data/2016/06/27/203165/preview16.jpg', 
     500, 
     9),
     
    ('Almond Milk', 
     'Unsweetened almond milk, dairy-free alternative.', 
     'This unsweetened almond milk is a delicious dairy-free alternative to traditional milk. Low in calories and rich in vitamins, it’s perfect for smoothies, coffee, or cereal.', 
     2.99, 
     2.50, 
     'https://upload.wikimedia.org/wikipedia/commons/9/93/Almond_Non-Dairy_Milk_%285082992066%29.jpg', 
     300, 
     9),
     
    ('Whole Grain Bread', 
     'Freshly baked whole grain bread.', 
     'This freshly baked whole grain bread is made with natural ingredients, providing a healthy source of fiber and essential nutrients. Perfect for sandwiches or toast, it offers great taste and nutrition.', 
     3.49, 
     2.99, 
     'https://live.staticflickr.com/65535/49325621857_cd9592619d_b.jpg', 
     250, 
     9),
     
    ('Extra Virgin Olive Oil', 
     'High-quality extra virgin olive oil.', 
     'Our extra virgin olive oil is cold-pressed and sourced from the finest olives. It adds rich flavor to salads, marinades, and cooking, making it a staple in any kitchen.', 
     8.99, 
     7.49, 
     'https://live.staticflickr.com/6107/7019001595_b3609d2776_c.jpg', 
     200, 
     9),
     
    ('Organic Quinoa', 
     'Nutritious organic quinoa, gluten-free grain.', 
     'Organic quinoa is a nutritious, gluten-free grain packed with protein and fiber. It\'s versatile and can be used in salads, side dishes, or as a base for a healthy meal.', 
     4.99, 
     3.99, 
     'https://i2.pickpik.com/photos/769/905/98/quinoa-grain-seed-food-preview.jpg', 
     150, 
     9),
     
    ('Frozen Mixed Vegetables', 
     'A mix of frozen vegetables for easy cooking.', 
     'Our frozen mixed vegetables are perfect for quick meals. They are harvested at the peak of freshness and flash-frozen to preserve flavor and nutrients, making them easy to add to stir-fries, soups, and casseroles.', 
     2.49, 
     1.99, 
     'https://live.staticflickr.com/6107/6298248101_e10e4837c1_b.jpg', 
     300, 
     9),
     
    ('Greek Yogurt', 
     'Creamy Greek yogurt, high in protein.', 
     'This creamy Greek yogurt is packed with protein and makes a perfect snack or breakfast option. Enjoy it plain or with your favorite fruits and nuts for a delicious treat.', 
     1.99, 
     1.50, 
     'https://live.staticflickr.com/7292/27667744923_e02133a896_b.jpg', 
     400, 
     9),
     
    ('Natural Peanut Butter', 
     'Creamy peanut butter made from natural ingredients.', 
     'Our natural peanut butter is made from 100% roasted peanuts, with no added sugars or oils. It’s perfect for spreading on toast, adding to smoothies, or enjoying straight from the jar.', 
     4.49, 
     3.99, 
     'https://live.staticflickr.com/5556/14939772517_8d083722ba_b.jpg', 
     200, 
     9),
     
    ('Cereal Granola', 
     'Crunchy granola cereal, perfect for breakfast.', 
     'This crunchy granola cereal is a delicious and nutritious way to start your day. Made with whole grains and a hint of honey, it’s perfect with milk or yogurt and topped with fresh fruits.', 
     3.99, 
     3.49, 
     'https://mir-s3-cdn-cf.behance.net/project_modules/1400/c7c3e762562203.5a948057bbd96.jpg', 
     300, 
     9),
     
    ('Dark Chocolate Bars', 
     'Rich dark chocolate bars, 70% cocoa.', 
     'Indulge in our rich dark chocolate bars made with 70% cocoa. These bars are perfect for satisfying your sweet tooth while providing the health benefits of dark chocolate.', 
     2.49, 
     1.99, 
     'https://live.staticflickr.com/46/157678562_50f13b5953_b.jpg', 
     250, 
     9);
     
     
     INSERT INTO Product 
    (name, description, long_description, price, discounted_price, image_url, stock, category_id) 
VALUES 
    ('Gold Hoop Earrings', 
     'Classic gold hoop earrings, 14k.', 
     'These classic 14k gold hoop earrings are a timeless accessory that adds elegance to any outfit. With a sleek design, they are perfect for everyday wear or special occasions.', 
     120.00, 
     100.00, 
     'https://images.pexels.com/photos/12145096/pexels-photo-12145096.jpeg', 
     150, 
     10),
     
    ('Silver Pendant Necklace', 
     'Stylish silver pendant necklace with cubic zirconia.', 
     'This stylish silver pendant necklace features a beautiful cubic zirconia stone that sparkles with every movement. A versatile piece, it can be worn for both casual and formal occasions.', 
     45.00, 
     35.00, 
     'https://i2.pickpik.com/photos/783/489/120/chain-trailers-fashion-jewelry-jewellery-preview.jpg', 
     200, 
     10),
     
    ('Diamond Engagement Ring', 
     'Stunning diamond engagement ring, 1 carat.', 
     'This stunning 1-carat diamond engagement ring features a classic solitaire design that highlights the beauty of the diamond. Crafted in 14k white gold, it is the perfect symbol of love and commitment.', 
     2500.00, 
     2300.00, 
     'https://upload.wikimedia.org/wikipedia/commons/7/78/Diamond_engagement_ring_in_a_twist_design.jpg', 
     50, 
     10),
     
    ('Leather Bracelet', 
     'Stylish leather bracelet with metal accents.', 
     'This stylish leather bracelet features metal accents and an adjustable clasp for a perfect fit. It’s a great accessory for both men and women, adding a touch of rugged charm to any outfit.', 
     30.00, 
     25.00, 
     'https://live.staticflickr.com/8447/7970981692_1c3c2e153d_z.jpg', 
     100, 
     10),
     
    ('Sapphire Stud Earrings', 
     'Elegant sapphire stud earrings, 2 carats.', 
     'These elegant sapphire stud earrings are set in 14k white gold and feature a total weight of 2 carats. Perfect for adding a pop of color to any look, they are a must-have for any jewelry collection.', 
     500.00, 
     450.00, 
     'https://live.staticflickr.com/3122/2551938768_bf71139490_z.jpg', 
     75, 
     10),
     
    ('Pearl Necklace', 
     'Classic pearl necklace with a modern twist.', 
     'This classic pearl necklace is crafted with high-quality freshwater pearls, strung together with a modern clasp for a contemporary touch. Ideal for special occasions or everyday elegance.', 
     200.00, 
     180.00, 
     'https://live.staticflickr.com/74/196884152_1ccdc1ce8d_b.jpg', 
     50, 
     10),
     
    ('Vintage Brooch', 
     'Beautiful vintage brooch with intricate detailing.', 
     'This beautiful vintage brooch features intricate detailing and a unique design that makes it a standout accessory. Perfect for adding a touch of nostalgia to any outfit.', 
     75.00, 
     60.00, 
     'https://live.staticflickr.com/7101/7369117920_e2ba16ab2d_c.jpg', 
     30, 
     10),
     
    ('Amethyst Ring', 
     'Stunning amethyst ring set in sterling silver.', 
     'This stunning amethyst ring features a beautiful deep purple stone set in high-quality sterling silver. It’s a perfect choice for those who love unique and vibrant jewelry.', 
     150.00, 
     125.00, 
     'https://i0.pickpik.com/photos/690/497/103/amethyst-white-gold-diamond-vintage-preview.jpg', 
     100, 
     10),
     
    ('Crystal Choker', 
     'Fashionable crystal choker necklace.', 
     'This fashionable crystal choker necklace adds a trendy touch to any outfit. The sparkling crystals catch the light beautifully, making it a perfect accessory for parties or nights out.', 
     25.00, 
     20.00, 
     'https://i2.pickpik.com/photos/372/803/821/jewellery-fashion-jewelry-shiny-decorative-preview.jpg', 
     200, 
     10),
     
    ('Titanium Wedding Band', 
     'Durable titanium wedding band with a matte finish.', 
     'This durable titanium wedding band features a sleek matte finish, symbolizing love and commitment. Its modern design makes it a popular choice for couples looking for something unique.', 
     150.00, 
     130.00, 
     'https://pixnio.com/free-images/2020/07/28/2020-07-28-11-09-16-1200x800.jpg', 
     100, 
     10);

INSERT INTO Product 
    (name, description, long_description, price, discounted_price, image_url, stock, category_id) 
VALUES 
    ('Neutrogena Hydro Boost Water Gel', 
     'Lightweight moisturizer with hyaluronic acid.', 
     'Neutrogena Hydro Boost Water Gel is a lightweight moisturizer that provides intense hydration with hyaluronic acid. It absorbs quickly, leaving skin feeling refreshed and smooth without any greasy residue, perfect for daily use.', 
     34.99, 
     29.99, 
     'https://live.staticflickr.com/4660/40179166182_5678a2c7fd_z.jpg', 
     200, 
     6),
     
    ('Olay Regenerist Micro-Sculpting Cream', 
     'Anti-aging cream with hyaluronic acid and amino-peptides.', 
     'Olay Regenerist Micro-Sculpting Cream is an advanced anti-aging cream formulated with hyaluronic acid and amino-peptides. It hydrates and firms the skin, reducing the appearance of fine lines and wrinkles for a more youthful look.', 
     49.99, 
     39.99, 
     'https://live.staticflickr.com/5002/5289857328_05e668d7b7_b.jpg', 
     150, 
     6),
     
    ('Maybelline New York Fit Me Matte + Poreless Foundation', 
     'Liquid foundation for a natural matte finish.', 
     'Maybelline New York Fit Me Matte + Poreless Foundation offers a natural matte finish that blends seamlessly into the skin. Its lightweight formula controls shine and minimizes the appearance of pores, making it ideal for everyday wear.', 
     10.99, 
     8.99, 
     'https://static.openbeautyfacts.org/images/products/360/053/132/5138/front_en.3.full.jpg', 
     300, 
     6),
     
    ('L’Oreal Paris Voluminous Lash Paradise Mascara', 
     'Lengthening mascara for voluminous lashes.', 
     'L’Oreal Paris Voluminous Lash Paradise Mascara delivers stunning length and volume to your lashes with its soft wavy bristle brush. The rich formula glides on smoothly, ensuring no clumps for beautifully defined lashes.', 
     9.99, 
     7.99, 
     'https://i2.pickpik.com/photos/215/476/1017/cosmetics-make-up-makeup-beauty-preview.jpg', 
     250, 
     6),
     
    ('CeraVe Hydrating Cleanser', 
     'Gentle cleanser for normal to dry skin.', 
     'CeraVe Hydrating Cleanser is a gentle, non-foaming formula that effectively removes makeup and impurities without stripping the skin’s natural moisture. It contains essential ceramides and hyaluronic acid to hydrate and nourish.', 
     15.99, 
     12.99, 
     'https://static.openbeautyfacts.org/images/products/333/787/579/5456/front_fr.3.full.jpg', 
     200, 
     6),
     
    ('The Ordinary Niacinamide 10% + Zinc 1%', 
     'Serum for reducing blemishes and controlling oil.', 
     'The Ordinary Niacinamide 10% + Zinc 1% is a lightweight serum that helps to reduce the appearance of blemishes and congestion while balancing visible sebum activity. It’s ideal for oily and combination skin types.', 
     6.50, 
     5.50, 
     'https://images.pexels.com/photos/14920158/pexels-photo-14920158.jpeg', 
     180, 
     6),
     
    ('Mario Badescu Facial Spray with Aloe, Herbs, and Rosewater', 
     'Refreshing facial mist for hydration and radiance.', 
     'Mario Badescu Facial Spray with Aloe, Herbs, and Rosewater is a refreshing mist that hydrates and revitalizes the skin. Perfect for setting makeup or as a midday pick-me-up, it leaves skin feeling dewy and radiant.', 
     7.00, 
     5.50, 
     'https://d3pllp7nz3wmw5.cloudfront.net/product_images/MPHARMR_oborne_EBAY_SMALL_US.jpg', 
     250, 
     6),
     
    ('Nivea Soft Moisturizing Cream', 
     'Lightweight moisturizer for face, body, and hands.', 
     'Nivea Soft Moisturizing Cream is a refreshing, lightweight cream that provides intense moisture for the face, body, and hands. Its fast-absorbing formula makes it perfect for daily hydration.', 
     9.99, 
     8.00, 
     'https://static.openbeautyfacts.org/images/products/502/597/000/4761/front_en.6.full.jpg', 
     300, 
     6),
     
    ('Kiehl’s Ultra Facial Cream', 
     '24-hour daily hydrating cream for all skin types.', 
     'Kiehl’s Ultra Facial Cream provides long-lasting hydration and is formulated to maintain skin’s moisture balance. It’s lightweight and absorbs quickly, suitable for all skin types.', 
     36.00, 
     30.00, 
     'https://static.openbeautyfacts.org/images/products/360/597/154/5672/front_en.4.full.jpg', 
     150, 
     6),
     
    ('Dove Body Wash Deep Moisture', 
     'Creamy body wash for nourished and hydrated skin.', 
     'Dove Body Wash Deep Moisture is a creamy, hydrating body wash that nourishes and hydrates the skin while you cleanse. Infused with skin-natural nutrients, it leaves your skin feeling soft and smooth.', 
     7.99, 
     6.50, 
     'https://static.openbeautyfacts.org/images/products/871/160/036/8804/front_en.3.full.jpg', 
     400, 
     6);
     
INSERT INTO Product 
    (name, description, long_description, price, discounted_price, image_url, stock, category_id) 
VALUES 
    ('Nike Dri-FIT Training T-Shirt', 
     'Breathable training t-shirt with moisture-wicking technology.', 
     'The Nike Dri-FIT Training T-Shirt is designed for comfort and performance during workouts. Made with breathable fabric and moisture-wicking technology, it keeps you dry and comfortable, whether you’re hitting the gym or running outdoors.', 
     30.00, 
     25.00, 
     'https://live.staticflickr.com/4012/4667536795_27a8632fd3_b.jpg', 
     250, 
     7),
     
    ('Adidas Essentials 3-Stripes Track Pants', 
     'Comfortable track pants with a classic 3-stripes design.', 
     'The Adidas Essentials 3-Stripes Track Pants offer a relaxed fit and classic look, perfect for workouts or casual wear. Made from soft fabric, they feature an elastic waistband and side pockets for added convenience.', 
     45.00, 
     39.99, 
     'https://upload.wikimedia.org/wikipedia/commons/0/0d/Tracksuit_pants_%28AM_2017.66.26-5%29.jpg', 
     200, 
     7),
     
    ('Under Armour Charged Assert 8 Running Shoes', 
     'Lightweight running shoes with responsive cushioning.', 
     'The Under Armour Charged Assert 8 Running Shoes are designed for comfort and performance. Featuring lightweight construction and responsive cushioning, they provide excellent support for both running and everyday wear.', 
     85.00, 
     75.00, 
     'https://i0.pickpik.com/photos/589/84/958/running-shoe-shoe-asics-highly-functional-preview.jpg', 
     180, 
     7),
     
    ('Champion Powerblend Fleece Hoodie', 
     'Cozy hoodie made from a soft fleece blend.', 
     'The Champion Powerblend Fleece Hoodie is perfect for cooler weather, made from a soft fleece blend that provides warmth and comfort. Featuring a spacious hood and kangaroo pocket, it’s ideal for both workouts and lounging.', 
     50.00, 
     44.99, 
     'https://cdn.printerval.com/unsafe/960x960/asset.prtvstatic.com/files/60c6f8dbb0ff73.14327126.jpg', 
     150, 
     7),
     
    ('YETI Rambler 20 oz Tumbler', 
     'Durable tumbler that keeps drinks hot or cold.', 
     'The YETI Rambler 20 oz Tumbler is built to handle tough conditions, keeping drinks hot or cold for hours. Made from kitchen-grade stainless steel, it features double-wall vacuum insulation and a no-sweat exterior, perfect for outdoor adventures.', 
     29.99, 
     24.99, 
     'https://live.staticflickr.com/65535/49670546153_9b88f68ff2_b.jpg', 
     100, 
     7),
     
    ('Coleman Portable Camping Chair', 
     'Lightweight and foldable camping chair for outdoor use.', 
     'The Coleman Portable Camping Chair is designed for comfort and convenience on the go. With a lightweight, foldable design, it’s easy to carry and set up. Perfect for camping, picnics, or watching outdoor events.', 
     24.99, 
     19.99, 
     'https://live.staticflickr.com/4145/4967947589_059f945b1b_b.jpg', 
     200, 
     7),
     
    ('Fitness Reality 1000 Super Max Weight Bench', 
     'Versatile weight bench for strength training exercises.', 
     'The Fitness Reality 1000 Super Max Weight Bench is designed for a variety of strength training exercises. With a sturdy frame and adjustable positions, it allows you to perform a range of workouts, from bench presses to leg lifts.', 
     119.99, 
     109.99, 
     'https://live.staticflickr.com/7008/6648563715_7518ff1a06_b.jpg', 
     80, 
     7),
     
    ('Intex Inflatable River Run II', 
     'Two-person inflatable lounge for relaxing on the water.', 
     'The Intex Inflatable River Run II is a two-person inflatable lounge designed for fun on the water. With built-in cup holders and a comfortable seating area, it’s perfect for relaxing while floating down rivers or enjoying a day at the beach.', 
     59.99, 
     49.99, 
     'https://i2.pickpik.com/photos/608/481/235/raft-whitewater-raft-boat-teamwork-preview.jpg', 
     150, 
     7),
     
    ('Wilson Evolution Game Basketball', 
     'High-quality basketball designed for indoor and outdoor play.', 
     'The Wilson Evolution Game Basketball is a top choice for players at all levels. With its premium composite leather cover, it offers excellent grip and durability for both indoor and outdoor play, making it ideal for practice or games.', 
     59.99, 
     54.99, 
     'https://pixnio.com/free-images/2019/04/20/2019-04-20-09-29-31.jpg', 
     250, 
     7),
     
    ('GoPro HERO9 Black', 
     'Compact and versatile action camera for capturing adventures.', 
     'The GoPro HERO9 Black is a powerful action camera that captures stunning 5K video and 20MP photos. With advanced stabilization and a waterproof design, it’s perfect for adventurers looking to document their experiences, whether on land or water.', 
     399.99, 
     349.99, 
     'https://negahshop.com/wp-content/uploads/2021/01/1600428045_1585844.jpg', 
     75, 
     7);


