services:
  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT:-7000}:6379"
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5