server:
  port: 9898

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

application:
  title: ecommerce-backend
  version: 1.0.0
