server:
  port: 9898

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        ddl-auto: update

logging:
  level:
    root: INFO
    com.app.ecommerce: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

application:
  title: ecommerce-backend
  version: 1.0.0

frontend:
  origin: http://localhost:3000