server:
  port: 9898

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format-sql: true


application:
  title: ecommerce-backend
  version: 1.0.0